title: "My Portfolio"
description: "A showcase of my projects, skills, and professional journey."
baseurl: ""
url: "https://LowerJacksonMound.github.io"
twitter_username: your-twitter-handle
github_username: LowerJacksonMound

theme: minima

plugins:
  - jekyll-feed

sass:
  sass_dir: assets/css


seo:
  title: "My Portfolio"
  description: "A showcase of my projects, skills, and professional journey."
  keywords: "developer, portfolio, projects, web development"
